### ISSUE TITLE
Cannot start zrobot

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/0-robot#24]
While trying to install and start zrobot, I got the following error:

```
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/zrobot", line 5, in <module>
    from zerorobot.cli.server import server
ImportError: No module named 'zerorobot.cli'
```

as far as I can see, there is no __init__.py in the cli directory so its not considered as a package.

**Comment by zaibon** [comment]
That is indeed true, there is no __init__.py in this folder. On the other hand I never hit this issue, neither travis did. 
@abdulrahmantkhalifa can you confirm adding the missing file solve the problem ?

**Comment by ahussein** [comment]
I am not abdulrahantkhalifa :) I am another abdelrahman
adding __init__.py file in the cli directory fixes the reported problem but then the same problem exist for the api directory. After adding another __init__.py to the api directory as well, I get the following error:

```
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/zrobot", line 5, in <module>
    from zerorobot.cli.server import server
  File "/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/cli/server.py", line 4, in <module>
    from zerorobot.robot import Robot
  File "/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/robot.py", line 20, in <module>
    from zerorobot.api.app import app
  File "/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/api/app.py", line 5, in <module>
    from .blueprints_api import blueprints_api
  File "/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/api/blueprints_api.py", line 14, in <module>
    Blueprint_schema = JSON.load(open(dir_path + '/schema/Blueprint_schema.json'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/api/schema/Blueprint_schema.json'
[Errno 2] No such file or directory: '/home/vagrant/venv/lib/python3.5/site-packages/zerorobot/api/schema/Blueprint_schema.json' 
```

I am not sure about your system, but as far as I can see, travis is configured to run the tests which I assume its only unittests where test code instantiate the main classes.

I would add a test script that starts the server as well as a bit of integration test.

**Comment by zaibon** [comment]
Sorry my bad for the wrong username.

Can you report here how you installed the app, so I can trace the problem.

**Comment by ahussein** [comment]
Steps to reproduces:

- Start from a fresh Ubuntu 14.04 vm image
- Execute the following steps:
```
# install python3.5 
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.5
sudo apt-get install -y python-pip python-dev build-essential python3.5-dev git
sudo pip install virtualenv
virtualenv -p python3.5 venv
source $HOME/venv/bin/activate
# cd to the 0-reobot directory
pip3 install -r requirements.txt
./utils/scripts/jumpscale_install.sh
pip3 install . -U
```

- Execute the zrobot binary
`zrobot --help`

**Comment by ahussein** [comment]
changes in https://github.com/Jumpscale/0-robot/pull/25 fixes the problems described above.
