### ISSUE TITLE
Implement kunernetes  templates

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/0-robot#30]
There will be 5 services to manage kubernetes:
- kube_master
- kube_node
- kube_cluster
- etcd_node
- etcd_cluster

### kube_master
- service will deploy the master node of kubernetes, it can be multiple master in a cluster.
- created and manged by kube_cluster

### kube_node
- service will deploy a minion node of kubernetes
- created and manged by kube_cluster

### kub_cluster
- this is the high level service user will deal with.
- can be created by user using blueprint or API
- deploys kub_master, kub_node, etcd_cluster

### etcd_cluster
- service will deploy etcd_node
- service can be created by user or by kub_cluster

### etcd_node
- will run an etcd server.
- need to support starting in a cluster mode

**Comment by zaibon** [comment]
blocked on : https://github.com/Jumpscale/prefab9/issues/160

**Comment by serboctor** [comment]
Moved to https://github.com/zero-os/0-templates/issues/2
