### ISSUE TITLE
Add connect to zrobot before using it with dsl in quickstart guide

### ISSUE THREAD

**Issue by chrisvdg** [Jumpscale/0-robot#57]
In the quickstart guide using dsl (https://github.com/Jumpscale/0-robot/blob/master/docs/quickstart.md#creating-instance-of-the-service-and-schedluing-actions-using-the-dsl) it doesn't mention connecting the zrobot before using it while it does seem to be required.

**Comment by zaibon** [comment]
@chrisvdg can you create a PR that upadte the doc ?
