### ISSUE TITLE
Service: add get/exist

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/0-robot#64]
In some cases we need to check if a service exists or event get the service and use it in another template.
Like the `services.find`, may be we can add `services.exist` and `services.get`.

**Comment by zaibon** [comment]
exists method could be added. But what argument would you want ? Same as the find ?
regarding service get, you can already get a service by id or by name, you need somehting else ?

**Comment by serboctor** [comment]
> exists method could be added. But what argument would you want ? Same as the find ?

Yes, that would be perfect.

> regarding service get, you can already get a service by id or by name, you need somehting else ?

Since names can be duplicated, I dont' think `services.names` will come in handy. I think it would be a good idea to have `services.get` with the same filters as the find. If the service exists, it returns the service, if it doesn't, returns None, and if multiple services were found, raises an error.

**Comment by zaibon** [comment]
> Since names can be duplicated, I dont' think services.names will come in handy. I think it would be a good idea to have services.get with the same filters as the find. If the service exists, it returns the service, if it doesn't, returns None, and if multiple services were found, raises an error.

You prefer that `get` returns non if service not found, or also raises an exception ?
I find it more consistent if both case not found and too many results both raises

**Comment by serboctor** [comment]
> You prefer that get returns non if service not found, or also raises an exception ?
I find it more consistent if both case not found and too many results both raises

good point....let's keep them consistent. After all a try/except can be avoided by using the `exist` function anyway.
