### ISSUE TITLE
inter-robot gossip protocol

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/0-robot#87]
Currently when you deploy a robot, you need to manually configure the connection to other robot if you want the robots to be able to interact with each other. This task is tedious as soon as you start to have a lot of robot. Also this model doesn't allow for the already running robot to be notify that a new robot is present in the grid.

To solve this I was thinking implementing some sort of gossiping between the robot so they could exchange information about the other robot they know. Like that, the only think you would have to do to plug a new robot to a grid is to point him to at leat one robot, and it will discover all other robots, and other robot will be aware of the new one automatically

**Comment by muhamadazmy** [comment]
The concept is totally fine, except that it will be hard to find out where a specific robot is plugged to the grid, which can make it really hard to take one out. 

I would recommend a `service discovery` protocol where a robot announce itself and others can know about it by implementing one of the known service discovery protocols. 

This of course depends on how the robots are gonna be reachable to each other, is it local network (or zerotier) or they only reach over public ip/nat. The service discovery works only on local networks (and i think zerotier as well, we need to check)

**Comment by zaibon** [comment]
I've a WIP concept on https://github.com/Jumpscale/0-robot/commit/4c37f696e1d5c7c4bfb281ca30e53907b8eda941
The idea is that a robot can announce itself to all the robot he already knows. Then there is an hanshake between robot to validate indentify.

Then I've in mind to do some kind of automating sharing of known robots. Something like, when a robot receive an announce of a new robot, and the handshake went ok, this robot will broadcast this announce to all the robot it knows, so the announce of the new robot will propagate through the grid till every robot is aware a new robot join the grid.

**Comment by zaibon** [comment]
Closing this cause we won't need to propagate when a new robot join the grid.
Replaced with https://github.com/Jumpscale/0-robot/issues/111
